name: Format With Prettier

on:
  push:
    branches:
      - main
      - Auto-Formatting
  pull_request:
    branches:
      - main
      - Auto-Formatting

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set Up Mid JS Framework
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Fix permissions
      run: chmod +x node_modules/.bin/prettier

    - name: Apply Prettier
      run: npx prettier --write "**/*.java"

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m 'Apply Prettier format' || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
